### ISSUE TITLE
panics on my machine

### ISSUE THREAD

**Issue by fopsdev** [will-hart/ld47#1]
hi there

wanted to give Obelisk a test-spin. Downloaded the .exe and ran it:

![image](https://user-images.githubusercontent.com/5448300/95102221-6c803480-0733-11eb-8e75-be57c406909c.png)

just leeme know if you need further details.
you can find my dxdiag file here:
https://github.com/bevyengine/bevy/issues/366
:)

**Comment by will-hart** [comment]
Hey, thanks for the report. 

Its a bit hard to gather anything from the screenshot. From the other issue you linked are you saying this is the same issue? If so it seems like a bevy issue?

If its something different happy to take a look just need a bit more to go on.

**Comment by will-hart** [comment]
Actually just tried on another machine (with integrated graphics) and it looks like it might be related to this https://github.com/bevyengine/bevy/issues/130

Will see if I can work out a fix

**Comment by fopsdev** [comment]
Hi

No the issue is not related to this one. i've just mentioned it because you can find the dxdiag file there.
not sure if it helps but this is happening when i start:  it opens 2 empty windows (1 console, 1 bevy main window) the screenshot is from the console window, bevy window stays empty. right after the start it crashes.
Wish you good luck hunting down the bug

**Comment by will-hart** [comment]
Should be resolved by https://github.com/will-hart/ld47/releases/tag/1.1.3

Thanks again for reporting
